EmrPuriBunda/Controllers/ObatDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EmrPuriBunda.Models;
using Microsoft.AspNetCore.Authorization;
using Mahas.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace EmrPuriBunda.Controllers
{
    [Authorize]
    public class ObatDetailController : Controller
    {
        private IConfiguration Config { get; set; }
        public ObatDetailController(IConfiguration configuration) => Config = configuration;

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Datas_ObatDetail(int pageSize, int pageIndex, int orderBy, OrderByTypeEnum orderByType, List<FilterModel> filter)
        {
            try
            {
                var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                int totalRowCount;
                List<ObatDetail_ObatDetail_ListModel> datas;

                using (var s = new MahasConnection(Config.GetConnectionString("EmrPuriBundaConnection")))
                {
                    var parameters = new List<SqlParameter>();
                    var wheres = new List<string>();
                    var _orderBy = new List<string>()
                    {
                        "Kode_Barang",						"Nama_Barang",						"JmlObat",						"Dosis"
                    };

                    foreach (var x in filter)
                    {
                        switch (x.Key)
                        {
                            case "NoReg":
                                if (string.IsNullOrEmpty(x.Value)) break;
                                parameters.Add(new SqlParameter($"@NoReg", $"{x.Value}"));
                                wheres.Add($"(NoReg = @NoReg)");
                                break;
                            case "NoBukti":
                                if (string.IsNullOrEmpty(x.Value)) break;
                                parameters.Add(new SqlParameter($"@NoBukti", $"{x.Value}"));
                                wheres.Add($"(NoBukti = @NoBukti)");
                                break;
                        }
                    }

                    var query = $@"
                        SELECT
                            *
                        FROM
                            Vw_Obat_Detail
                        {s.ToWhere(wheres)}
                    ";

                    totalRowCount = await s.GetTotalRowConst(query, parameters);
                    datas = await s.GetDatas<ObatDetail_ObatDetail_ListModel>(query, _orderBy[orderBy], orderByType,  pageIndex, pageSize, parameters);
                }

                return Json(new
                {
                    Success = true,
                    Datas = datas,
                    PageIndex = pageIndex,
                    PageSize = pageSize,
                    TotalCount = totalRowCount
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false,
                    ex.Message
                });
            }
        }
    }
}

EmrPuriBunda/Views/ObatDetail/Index.cshtml
<div id="table_ObatDetail">

    <div class="card-header">
        <dl class="row">
            <dt class="col-md-3">No Resep</dt>
            <dd id="table_ObatDetail_noResep" class="col-md-9"></dd>

            <dt class="col-md-3">No Bukti</dt>
            <dd id="table_ObatDetail_noBukti" class="col-md-9"></dd>

            <dt class="col-md-3">Dokter</dt>
            <dd id="table_ObatDetail_dokter" class="col-md-9"></dd>
        </dl>
    </div>

    <div class="card-header header-elements-inline pt-2">
        <h5 class="card-title"></h5>

        <div class="header-elements">
            <div class="list-icons">
                <!--Modal Post-->
                <a class="list-icons-item" data-action="reload" href="javascript:itable_ObatDetail.refresh()"></a>
            </div>
        </div>
    </div>
    <form class="itable-form">
        @Html.AntiForgeryToken()
        <input type="hidden" class="itable-pagesize" value="20" />
        <input type="hidden" data-itable-filter="NoReg" value="@ViewData["NoReg"]" />
        <input type="hidden" data-itable-filter="NoBukti" />
        <input type="submit" class="d-none" />
    </form>

    <div>
        <table class="table table-hover dataTable table-xs table-striped">
            <thead>
                <tr class="bg-indigo-400">
                    <th class="sorting text-left" data-itable-sorting="0">Kode Barang</th>
                    <th class="sorting text-left" data-itable-sorting="1" style="width: 40%">Nama Barang</th>
                    <th class="sorting text-center" data-itable-sorting="2">Jml Obat</th>
                    <th class="sorting text-left" data-itable-sorting="3" style="width: 35%">Dosis</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<!--Custom HTML-->

<script>
    let itable_ObatDetail;
    document.addEventListener("DOMContentLoaded", function (event) {

        itable_ObatDetail = new iTable({
            id: 'table_ObatDetail',
            url: '@Url.Action("Datas_ObatDetail", "ObatDetail")',
            urlType:{
                DELETE : '@Url.Action("ObatDetail")'
            },
            orderBy: 0,
            success: (r, t) => {
                if (r.success) {
                    let tbody = '';
                    if (r.datas.length === 0) tbody += t.trempty();
                    $.each(r.datas, (i, v) => {
                        tbody += '<tr>';

                        // JS Columns
						tbody += `<td class="text-left">${v.kode_Barang}</td>`;
						tbody += `<td class="text-left">${v.nama_Barang}</td>`;
						tbody += `<td class="text-center">${v.jmlObat}</td>`;
						tbody += `<td class="text-left">${v.dosis}</td>`;
                        // ----- JS Columns

                        tbody += '</tr>';
                    });
                    $(t.id).find('tbody').html(tbody);
                    t.generateTableFooter(r.totalCount, r.pageSize, r.pageIndex);
                }
            }
        });

        itable_ObatDetail.fillHeader = header => {

            jForm = $(itable_ObatDetail.id);

            jForm.find(`[data-itable-filter='NoBukti']`)[0].value = header.noBukti;

            jForm.find('#table_ObatDetail_noResep').html(header.noResep);
            jForm.find('#table_ObatDetail_noBukti').html(header.noBukti);
            jForm.find('#table_ObatDetail_dokter').html(header.dokter);

            itable_ObatDetail.refresh();

        }

        customJS_ObatDetail();
    });

    const customJS_ObatDetail = () => {
        // JS Custom
        // ----- JS Columns
    };
</script>

<!--partial-->