EmrPuriBunda/Controllers/HasilBacaLabController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EmrPuriBunda.Models;
using Microsoft.AspNetCore.Authorization;
using Mahas.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace EmrPuriBunda.Controllers
{
    [Authorize]
    public class HasilBacaLabController : Controller
    {
        private IConfiguration Config { get; set; }
        public HasilBacaLabController(IConfiguration configuration) => Config = configuration;

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Datas_HasilBacaLab(int pageSize, int pageIndex, int orderBy, OrderByTypeEnum orderByType, List<FilterModel> filter)
        {
            try
            {
                var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                int totalRowCount;
                List<HasilBacaLab_HasilBacaLabModel> datas;

                using (var s = new MahasConnection(Config.GetConnectionString("EmrPuriBundaConnection")))
                {
                    //TODO : SECTION HARUS BUAT CONFIGNYA AGAR DINAMIS

                    var wheres = new List<string>()
                    {
                        "SectionID IN ('SEC005','SECT0020')"
                    };

                    var parameters = new List<SqlParameter>();
                    var _orderBy = new List<string>()
                    {
                        "Tanggal",						"DokterPengirim",						"SectionName",						"PenanggungJawab"
                    };

                    foreach (var x in filter)
                    {
                        switch (x.Key)
                        {
                            //case "NoReg":
                            //    if (string.IsNullOrEmpty(x.Value)) break;
                            //    parameters.Add(new SqlParameter($"@NoReg", $"{x.Value}"));
                            //    wheres.Add($"RegNo = @NoReg");
                            //    break;
                            case "NRM":
                                if (string.IsNullOrEmpty(x.Value)) break;
                                parameters.Add(new SqlParameter($"@NRM", x.Value));
                                break;
                        }
                    }

                    var query = $@"
                        SELECT
                            *
                        FROM
                            EMR_ListDataHasilPenunjang (@NRM)
                        {s.ToWhere(wheres)}
                    ";

                    totalRowCount = await s.GetTotalRowConst(query, parameters);
                    datas = await s.GetDatas<HasilBacaLab_HasilBacaLabModel>(query, _orderBy[orderBy], orderByType,  pageIndex, pageSize, parameters);
                }

                return Json(new
                {
                    Success = true,
                    Datas = datas,
                    PageIndex = pageIndex,
                    PageSize = pageSize,
                    TotalCount = totalRowCount
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false,
                    ex.Message
                });
            }
        }        [HttpGet]
        [ActionName("ActionHasilBacaLab")]
        public async Task<JsonResult> Data_HasilBacaLab(string NoReg, string NoSystem)
        {
            try
            {
                var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                HasilBacaLab_HasilBacaLabSetupModel data;
                using (var s = new MahasConnection(Config.GetConnectionString("SIMConnection")))
                {
                    var query = $@"
                        SELECT
                            TOP 1 *
                        FROM
                            EMR_VIEW_LABORATORIUM
                        WHERE
                            RegNo=@NoReg AND
                            NoSystem = @NoSystem
                    ";

                    data = await s.GetData<HasilBacaLab_HasilBacaLabSetupModel>(query, new List<SqlParameter>
                    {
                        new SqlParameter("@NoSystem", NoSystem),
                        new SqlParameter("@NoReg", NoReg)
                    });

                    
                }
                if (data == null) throw new Exception("Data tidak ditemukan");
                return Json(new
                {
                    Success = true,
                    Data = data,
                });
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false,
                    ex.Message
                });
            }
        }
    }
}

EmrPuriBunda/Views/HasilBacaLab/DokumenLab.cshtml
@{
    var pasien = ViewData["Pasien"] as EmrPuriBunda.Models.Pasien_PasienRegistrasiModel;
}

<!-- CSS CUSTOM -->

<div id="modal_dokumenLab" class="modal fade">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header bg-slate">
                <h6 class="modal-title"><label class="itable-title-type"></label>Hasil Lab</h6>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <form autocomplete="off">
                @Html.AntiForgeryToken()
                <div class="modal-body">

                    <input type="hidden" name="NoBukti">

                    <div class="row">

                        <div class="col-md">

                            <dl class="row">

                                <dt class="col-md-3">No. Input</dt>
                                <dd id="modal_dokumenLab_NoLab" class="col-md-9"></dd>

                                <dt class="col-md-3">Dokter Pengirim</dt>
                                <dd id="modal_dokumenLab_DokterPengirim" class="col-md-9"></dd>

                                <dt class="col-md-3">Nama Pemeriksaan</dt>
                                <dd id="modal_dokumenLab_Pemeriksaan" class="col-md-9"></dd>

                                <dt class="col-md-3">Waktu Pemeriksaan</dt>
                                <dd id="modal_dokumenLab_WaktuPemeriksaan" class="col-md-9"></dd>

                                <dt class="col-md-3">Hasil Baca</dt>
                                <dd id="modal_dokumenLab_HasilBaca" class="col-md-9"></dd>
                            </dl>

                        </div>

                        <div class="col-md">

                            <div class="form-group">
                                <label for="modal_dokumenLab_hasil_Komentar">Komentar</label>
                                <textarea required id="modal_dokumenLab_hasil_Komentar" name="Komentar" class="form-control text-left"></textarea>
                            </div>

                            <div class="form-check text-right">
                                <input type="checkbox" class="form-check-input" id="modal_dokumenLab_hasil_SudahDibaca" name="Dibaca">
                                <label class="form-check-label" for="modal_dokumenLab_hasil_SudahDibaca">Sudah Dibaca</label>
                            </div>
                        </div>

                    </div>


                    <div class="form-group text-right">
                        <button type="submit" class="btn bg-primary show-only-type-post show-only-type-put">Save</button>
                    </div>

                    <ul class="nav nav-tabs nav-tabs-highlight" id="modal_dokumenLab_listDokumen">
                    </ul>

                    <div class="tab-content">
                        <div id="dokumenLab_pdfContainer" class="tab-pane show active">

                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>

<script>
    let isetup_DokumenLab;
    document.addEventListener("DOMContentLoaded", function (event) {
        isetup_DokumenLab = new iSetup({
            id: 'modal_dokumenLab',
            url : '@Url.Action("KomentarPenunjang", "InputHasilPenunjang")',
            param: e => ({
                NoBukti: e.target['NoBukti'].value,
                model: {
                    ...getModelFromForm(e.target, isetup_DokumenLab),

                }
            }),
            success: (r, t) => {
                if (r.success) {
                    $(t.id).modal('hide');
                    //itable_StatusPsikologi.refresh();
                }
            },
            modalDataOnSuccess: (r, t) => {
                const form = $(t.id).find('form')[0];

                setFormFromModel(form, r.data, t);

                let child = ''

                $.each(r.data.tablePathDokumen, (i, v) => {
                    const active = i == 0 ? 'active' : '';
                    child += `<li class="nav-item"><a href="javascript:void(0);" onclick="isetup_DokumenLab.changeDokumen('${v.urlDokumen}')" data-key="${v.urlDokumen}" class="nav-link ${active}" data-toggle="tab">${v.fileName}</a></li>`;
                });

                $(isetup_DokumenLab.id).find('#modal_dokumenLab_listDokumen').html(child);

                const defaultKey = r.data.tablePathDokumen[0] ? r.data.tablePathDokumen[0].urlDokumen : '';

                if (defaultKey) {
                    isetup_DokumenLab.changeDokumen(defaultKey);
                }

                $(isetup_DokumenLab.id).find('#modal_dokumenLab_NoLab').html(r.data.noBukti);
                $(isetup_DokumenLab.id).find('#modal_dokumenLab_DokterPengirim').html(r.data.dokterID_Text);
                $(isetup_DokumenLab.id).find('#modal_dokumenLab_Pemeriksaan').html(r.data.pemeriksaan);
                $(isetup_DokumenLab.id).find('#modal_dokumenLab_WaktuPemeriksaan').html(dateToString(r.data.tanggalPeriksa, "dd-MM-yyyy HH:mm"));
                $(isetup_DokumenLab.id).find('#modal_dokumenLab_HasilBaca').html(r.data.hasilBaca);

            },
            modalOnReady: (e, t) => {
				const form = $(t.id).find('form')[0];

				if (t.type === 'POST') {

				}
			}
        });

        customJSSetup_DokumenLab();

        isetup_DokumenLab.changeDokumen = (url) => {

            const container = $('#dokumenLab_pdfContainer');
            container.html(`
                <object id="id_pdf" data=${url} type="application/pdf" width="100%" height="800px"></object>
            `);

        }
    });

    const customJSSetup_DokumenLab = () => {

        $.ui.fancytree.debugLevel = 0;

    };
</script>

EmrPuriBunda/Views/HasilBacaLab/Index.cshtml
@{ ViewData["Title"] = "Hasil Baca Lab";
    ViewData["Breadcrumb"] = new List<SelectListItem>() { new SelectListItem((string)ViewData["Title"], "active")

}; }

@{ var pasien = ViewData["Pasien"] as EmrPuriBunda.Models.RegistrasiPasien_DataReg; }

<!-- CSS CUSTOM -->

<div id="hasilBacaLab_table_HasilBacaLab">
    <div class="card-header header-elements-inline pt-1">
        <div class="card-title"></div>
        <div class="header-elements">
            <div class="list-icons">
                <!--Modal Post-->
                <a class="list-icons-item" data-action="reload" href="javascript:itable_HasilBacaLab.refresh()"></a>
            </div>
        </div>
    </div>
    <form class="itable-form">
        @Html.AntiForgeryToken()
        <input type="hidden" class="itable-pagesize" value="20" />
        <input type="hidden" data-itable-filter="NoReg" value="@ViewData["NoReg"]" />
        <input type="hidden" data-itable-filter="NRM" value="@pasien.NRM" />
        <input type="submit" class="d-none" />
    </form>
    <div>
        <table class="table table-hover dataTable table-striped">
            <thead>
                <tr class="">
                    <th class="text-center" style="width: 30px;">Action</th>
                    <th class="sorting text-center" data-itable-sorting="0">Tanggal</th>
                    <th class="text-left"></th>
                    <th class="text-left">Pemeriksaan</th>
                    <th class="sorting text-left" data-itable-sorting="1">Dokter Pengirim</th>
                    <th class="text-left">Dibaca</th>
                    <th class="text-left">Komentar</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>

<!--Custom HTML-->

<script>
    let itable_HasilBacaLab;
    document.addEventListener("DOMContentLoaded", function (event) {

        itable_HasilBacaLab = new iTable({
            id: 'hasilBacaLab_table_HasilBacaLab',
            url: '@Url.Action("Datas_HasilBacaLab", "HasilBacaLab")',
            orderBy: 0,
            orderByType: false,
            success: (r, t) => {
                if (r.success) {
                    let tbody = '';
                    if (r.datas.length === 0) tbody += t.trempty();
                    $.each(r.datas, (i, v) => {

                        tbody += '<tr>';

                        let header = `{ 
                            noSystem: '${v.noSystem}',
                            dokterPengirim: '${v.dokterPengirim}',
                            analis: '${v.analis}',
                            penanggungJawab: '${v.penanggungJawab}',
                            pemeriksaan: '${v.pemeriksaan}',
                            tanggal: '${v.tanggal}'
                        }`;

                        // JS Action
                        if (v.sourceData == 'DOKUMEN') {
                            tbody += `<td class="text-center"><a class="icon-eye" href="javascript:itable_HasilBacaLab.showDokumen({ NoBukti : '${v.noSystem}'})"></a></td>`;
                        } else {
                            tbody += `<td class="text-center"><a class="icon-eye" href="javascript:itable_HasilBacaLab.showHasilBacaDetail(${header})"></a></td>`;
                        }
                        // ----- JS Columns

                        // JS Columns
                        tbody += `<td class="text-center">${dateToString(v.tanggal, 'dd/MM/yyyy HH:mm')}</td>`;

                        const critical = v.criticalValue ? `<i class="icon-warning text-danger" data-toggle="tooltip" title="Critical Value"></i>` : '';
                        tbody += `<td class="text-center">${critical}</td>`;

                        tbody += `<td class="text-left">${v.pemeriksaan}</td>`;
                        tbody += `<td class="text-left">${v.dokterPengirim}</td>`;

                        const dibaca = v.dibaca ? `<input type='checkbox' onclick='return false;' checked>` : `<input type='checkbox' disabled>`

                        tbody += `<td class="text-center">${dibaca}</td>`;

                        tbody += `<td class="text-left">${v.komentar}</td>`;
                        // ----- JS Columns

                        tbody += '</div>';
                        tbody += '</div>';
                        tbody += '</div>';
                        tbody += '</td>';
                        tbody += '</tr>';
                    });
                    $(t.id).find('tbody').html(tbody);
                    t.generateTableFooter(r.totalCount, r.pageSize, r.pageIndex);
                }
            }
        });

        itable_HasilBacaLab.refresh();

        itable_HasilBacaLab.showDokumen = (obj) => {

            isetup_DokumenLab.openModal('PUT', obj);
        }

        itable_HasilBacaLab.showHasilBacaDetail = (header) => {

            isetup_HasilBacaDetail.fillHeader(header);

            isetup_HasilBacaDetail.openModal('PUT', { NoBukti: header.noSystem });
        }

        customJS_HasilBacaLab();
    });

    const customJS_HasilBacaLab = () => {

    };
</script>

@await Html.PartialAsync("~/Views/HasilBacaLabDetail/SetupHasilBacaLabDetail.cshtml", new ViewDataDictionary(ViewData))
@await Html.PartialAsync("~/Views/HasilBacaLab/DokumenLab.cshtml", new ViewDataDictionary(ViewData))